### ISSUE TITLE
Update all docs to refer to store-core

### ISSUE THREAD

**Issue by berezovskyi** [eclipse/lyo-store#8]
Previously we called it a `lyo-store` library. Now we have bigger plans for it (eg #3), so `lyo.store` is not the group name and the artifact is `store-core`. Wiki, READMEs, Javadoc `package.html` need to be updated.

**Comment by berezovskyi** [comment]
@jadelkhoury @jamsden would you be able to help? Would be also good to have you at least look at all those doc pages.

**Comment by jadelkhoury** [comment]
Some questions first:
1. by "so lyo.store is not the group name", you mean "so lyo.store is now the group name", right?
2. wouldn't org.eclipse.lyo.store be a more appropriate group name?
3. where should we place the wiki & javadocs? here on github?

I can do this task, if we can first draw a plan together on a white board. I see the following that needs to be updated:
A. the instructions https://wiki.eclipse.org/Lyo/Store (easy task, but again, where should it reside?)
B. the javadocs on http://assume.gitlab.io/jena-cache/apidocs/overview-summary.html (how do we handle javadocs in general?)
 
If we discuss when I am back at work, I am happy to do it.
